name: docker build

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        working-directory: .
        run: |
          docker buildx build --platform linux/amd64 -t gwbc/proxyscotch:amd64 -f Dockerfile . --push   
          docker buildx build --platform linux/arm64 -t gwbc/proxyscotch:arm64 -f Dockerfile . --push
